name: github-docker

on:
  push:
    branches: [release/1.0]

jobs:
  build-master-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login do DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image of master
        uses: docker/build-push-action@v2
        with:
          context: ./.github/workflows/
          file: ./.github/workflows/Dockerfile
          push: true
          tags: rombur/adamantine:1.0
